export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR'

export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_POPUP_LOCK = 'TOGGLE_POPUP_LOCK'

export const SESSIONS = 'SESSIONS'

export const TIME_TABLE = 'TIME_TABLE'
